### ISSUE TITLE
Ubuntu 14.04.03 ERROR 404

### ISSUE THREAD

**Issue by westmorjp** [makelinux/devstack-install-on-iso#2]
When attempting to run the devstack-install-on-iso script, the URL used by the script gets a 404 error.

It looks like the path to 14.04.03 has been removed from the URL pointed to by the current version of the script.

Specifically, http://releases.ubuntu.com/14.04.03/ is no longer accessible.

Line 7 of the script can be edited to accommodate a new image (e.g. ubuntu-14,04.4-server-amd64.iso) being assigned to iso_url, which resolves the 404 error and seems to work so far (although I am just beginning working with the stack...

I am not familiar enough with DevStack/OpenStack to know what kinds of dependency issues may arise from substituting another LTS version for the install, but assuming there are no issues that is the quick fix.

**Comment by makelinux** [comment]
When an image release is outdated, please just run with argument of updated release http://releases.ubuntu.com/14.04.4/ubuntu-14.04.4-server-amd64.iso.
