### ISSUE TITLE
install error 404: Not Found.

### ISSUE THREAD

**Issue by eddylai** [makelinux/devstack-install-on-iso#3]
$ ./devstack-install-on-iso 
--2017-03-07 08:36:59--  http://releases.ubuntu.com/14.04.4/ubuntu-14.04.4-server-amd64.iso
Resolving releases.ubuntu.com (releases.ubuntu.com)... 91.189.88.23, 2001:6b0:e:2018::1337
Connecting to releases.ubuntu.com (releases.ubuntu.com)|91.189.88.23|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-07 08:37:00 ERROR 404: Not Found.

**Comment by makelinux** [comment]
Fixed, thanks
