### ISSUE TITLE
Failed right away

### ISSUE THREAD

**Issue by thxmike** [makelinux/devstack-install-on-iso#4]
This failed right away on 14.04.5 with the following message

cat: /home/ubuntu/.ssh/id_rsa.pub: No such file or directory
./devstack-install-on-iso: line 39: mkisofs: command not found
./devstack-install-on-iso: line 43: qemu-img: command not found
./devstack-install-on-iso: line 44: qemu-system-x86_64: command not found

**Comment by makelinux** [comment]
Please try to install missing packages:

sudo apt-get install -y ssh genisoimage qemu-system-x86 qemu-utils

Thanks
